version: "3.7"

services:
  database:
    image: mysql:5.7
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: 150535
      MYSQL_DATABASE: bookstore_db
      MYSQL_USER: clarusway
      MYSQL_PASSWORD: Clarusway_1
    networks:
      - bookstorenet

  myapp:
    image: okermen/bookstoreapp:latest
    container_name: myapp
    restart: always
    depends_on:
      - database
    networks:
      - bookstorenet
    ports:
      - "80:80"
  
networks:
  bookstorenet:
    driver: bridge

  
